import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

/**
 * Wiki content collection.
 *
 * Articles live at src/content/<locale>/<contentType>/<slug>.mdx
 * The `id` generated by the glob loader is the path relative to base, without extension,
 * e.g. "en/bosses/emberfang".
 *
 * Frontmatter is validated at build time by the Zod schema below. A missing or
 * malformed field fails the build immediately.
 *
 * `image` uses the `image()` helper so covers are processed by Astro Image
 * (auto WebP/AVIF + responsive srcset). Frontmatter value is a path relative
 * to the MDX file, e.g. `image: '../../../assets/covers/emberfang-cover.svg'`.
 * At build time `entry.data.image` is `ImageMetadata | undefined`. For an
 * absolute og:image URL, read `.src` and prefix with `siteUrl`.
 */
const wiki = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/wiki' }),
  schema: ({ image }) =>
    z.object({
      title: z.string().max(80),
      description: z.string().min(40).max(165),
      category: z.string(),
      date: z.coerce.date(),
      lastModified: z.coerce.date().optional(),
      image: image().optional(),
      /** In-page hero image (public dir path, e.g. /images/creatures/x.webp).
       *  Distinct from `image`, which is the processed OG/cover asset. */
      heroImage: z.string().optional(),
      heroImageAlt: z.string().optional(),
      tags: z.array(z.string()).default([]),
      noindex: z.boolean().default(false),
      faq: z.array(z.object({ question: z.string(), answer: z.string() })).optional(),
    }),
});

export const collections = { wiki };
